# Generated by Django 5.1 on 2025-04-12 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Названия')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('profit', models.FloatField(default=0, verbose_name='Общая сумма выкупа')),
                ('telephone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='номер телефона')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.city', verbose_name='Место проживание')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
