# Generated by Django 5.2.14 on 2026-05-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_status_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('Приход', 'Приход'), ('Уход', 'Уход'), ('Переход', 'Переход')], max_length=10, verbose_name='Действие'),
        ),
    ]
