# Generated by Django 5.2.14 on 2026-05-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
