# Generated by Django 5.2.14 on 2026-05-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
