# Generated by Django 5.2.14 on 2026-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.CharField(choices=[('Да', 'Опубликовано'), ('Нет', 'Не опубликовано'), ('В пути', 'В пути'), ('Резерв', 'Резерв')], default='Нет', max_length=6, verbose_name='Статус'),
        ),
    ]
