# Generated by Django 5.2.14 on 2026-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['sell_price'], 'verbose_name': 'оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='price',
        ),
        migrations.AddField(
            model_name='equipment',
            name='buy_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена покупки'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sell_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Примерная цена продажи'),
        ),
    ]
