# Generated by Django 5.2.14 on 2026-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_remove_equipment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
