# Generated by Django 5.2.14 on 2026-05-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
