# Generated by Django 5.1 on 2025-05-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена'),
        ),
    ]
