# Generated by Django 5.1.7 on 2025-05-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resurce',
            options={'verbose_name': 'источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
