# Generated by Django 5.1.7 on 2025-05-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('review', '0002_alter_resurce_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент'),
        ),
    ]
