# Generated by Django 5.2.14 on 2026-05-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('profit', models.FloatField(default=0, verbose_name='Общая сумма выкупа')),
                ('telephone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='номер телефона')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.city', verbose_name='Место проживание')),
            ],
            options={
                'verbose_name': 'поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='SuplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('suplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.suplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
    ]
