# Generated by Django 5.2.14 on 2026-06-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='telephone2',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='номер телефона 2'),
        ),
    ]
