# Generated by Django 5.2.14 on 2026-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_transaction_order_from_supplier'),
        ('supplier', '0002_suplier_telephone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='categories',
            field=models.ManyToManyField(to='product.category', verbose_name='Категории'),
        ),
    ]
